"""
ml_classifier/training/train.py

Team 4 — fine-tune RoBERTa-base on LIAR (6-way truthfulness classes).

Consumes:
    team4_package/ml_classifier/datasets/processed/{train,validation}.csv
    team4_package/ml_classifier/datasets/metadata/label_mapping.json

Produces:
    team4_package/ml_classifier/training/checkpoints/best/
        -> Hugging Face model + tokenizer

    team4_package/ml_classifier/training/checkpoints/training_run.json
        -> training metadata, dataset version, metrics,
           hyperparameters, class distribution, class weights

Pipeline:
    Dataset preparation
        ↓
    Model training
        ↓
    Raw model
        ↓
    Calibration
        ↓
    Versioned model artifact
        ↓
    Friend's evaluation / model registry

Fixes applied vs previous version:
  - warmup_steps restored (warmup_ratio was silently dropped before due to
    an installed-version incompatibility). Training a pretrained transformer
    with zero warmup risks early instability; warmup_steps is computed
    manually here since it's a much older, more stable TrainingArguments
    field than warmup_ratio.
  - Class weights softened with sqrt() instead of raw inverse-frequency.
    Raw inverse-frequency weighting can overcorrect for LIAR's rare
    "pants-fire" class, producing large gradient swings early in training
    (worse without warmup, which is exactly what was happening before).
  - DataCollatorWithPadding added: dataset.py now tokenizes with
    padding=False, so batches must be padded dynamically here instead of
    every example being padded out to a fixed max_length regardless of
    its real length.
  - dataloader_num_workers / dataloader_pin_memory added for faster batch
    loading; gradient_accumulation_steps added so you can raise effective
    batch size without raising memory usage.

Run:
    python -m ml_classifier.training.train
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

import numpy as np
import torch
import yaml
from sklearn.metrics import accuracy_score, f1_score
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    DataCollatorWithPadding,
    EarlyStoppingCallback,
    Trainer,
    TrainingArguments,
    set_seed,
)

from ml_classifier.training.dataset import LiarDataset


logging.basicConfig(
    level=logging.INFO,
    format="%(levelname)s | %(message)s",
)

log = logging.getLogger("train")

CONFIG_PATH = Path(__file__).parent / "config.yaml"

PROJECT_ROOT = Path(__file__).parent.parent.parent.parent


class ClassWeightedTrainer(Trainer):
    """Hugging Face Trainer with (softened) inverse-frequency class weighting."""

    def __init__(self, *args, class_weights=None, **kwargs):
        self.class_weights = class_weights
        super().__init__(*args, **kwargs)

    def compute_loss(
        self,
        model,
        inputs,
        return_outputs=False,
        num_items_in_batch=None,
    ):
        labels = inputs.get("labels")

        outputs = model(**inputs)
        logits = outputs.get("logits")

        if self.class_weights is not None:
            weight = self.class_weights.to(logits.device)

            loss_fct = torch.nn.CrossEntropyLoss(
                weight=weight
            )

            loss = loss_fct(
                logits.view(-1, model.config.num_labels),
                labels.view(-1),
            )
        else:
            loss = outputs["loss"]

        return (
            (loss, outputs)
            if return_outputs
            else loss
        )


def load_config() -> dict:
    """Load configuration and resolve project-relative paths."""

    with open(CONFIG_PATH, encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    for key in [
        "data_dir",
        "label_mapping_path",
        "output_dir",
    ]:
        if key in cfg and not Path(cfg[key]).is_absolute():
            cfg[key] = str(PROJECT_ROOT / cfg[key])

    return cfg


def compute_metrics(eval_pred):
    """Compute validation metrics."""

    logits, labels = eval_pred

    preds = np.argmax(logits, axis=-1)

    return {
        "accuracy": accuracy_score(labels, preds),
        "f1_macro": f1_score(
            labels,
            preds,
            average="macro",
        ),
    }


def load_dataset_version(data_dir: Path) -> str:
    """Load dataset version generated by prepare_dataset.py."""

    version_file = data_dir / "version.yaml"

    if not version_file.exists():
        log.warning(
            f"Dataset version file not found: {version_file}"
        )
        return "unknown"

    with open(version_file, encoding="utf-8") as f:
        version_data = yaml.safe_load(f) or {}

    return version_data.get(
        "dataset_version",
        "unknown",
    )


def main():
    cfg = load_config()

    # --------------------------------------------------------------
    # Reproducibility
    # --------------------------------------------------------------

    set_seed(cfg["seed"])

    # --------------------------------------------------------------
    # Label mapping
    # --------------------------------------------------------------

    with open(
        cfg["label_mapping_path"],
        encoding="utf-8",
    ) as f:
        label_mapping = json.load(f)

    id_to_label = {
        int(k): v
        for k, v in label_mapping[
            "id_to_label"
        ].items()
    }

    label_to_id = label_mapping[
        "label_to_id"
    ]

    # --------------------------------------------------------------
    # Load tokenizer + model
    # --------------------------------------------------------------

    log.info(
        f"Loading base model: {cfg['model_name']}"
    )

    tokenizer = AutoTokenizer.from_pretrained(
        cfg["model_name"]
    )

    model = AutoModelForSequenceClassification.from_pretrained(
        cfg["model_name"],
        num_labels=cfg["num_labels"],
        id2label=id_to_label,
        label2id=label_to_id,
    )

    # --------------------------------------------------------------
    # Load processed datasets
    # --------------------------------------------------------------

    data_dir = Path(cfg["data_dir"])

    train_path = data_dir / "train.csv"
    validation_path = data_dir / "validation.csv"

    if not train_path.exists():
        raise FileNotFoundError(
            f"Training data not found: {train_path}. "
            "Run prepare_dataset.py first."
        )

    if not validation_path.exists():
        raise FileNotFoundError(
            f"Validation data not found: {validation_path}. "
            "Run prepare_dataset.py first."
        )

    use_metadata = cfg.get("use_metadata", True)
    log.info(f"Metadata features: {'enabled' if use_metadata else 'disabled'}")

    train_ds = LiarDataset(
        train_path,
        tokenizer,
        max_length=cfg["max_length"],
        use_metadata=use_metadata,
    )

    val_ds = LiarDataset(
        validation_path,
        tokenizer,
        max_length=cfg["max_length"],
        use_metadata=use_metadata,
    )

    log.info(
        f"Loaded datasets: "
        f"train={len(train_ds)}, "
        f"validation={len(val_ds)}"
    )

    # --------------------------------------------------------------
    # Dynamic padding collator
    # --------------------------------------------------------------
    #
    # dataset.py tokenizes with padding=False, so each batch needs to be
    # padded to its own longest sequence here instead of every example
    # being padded out to a fixed max_length regardless of real length.

    data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

    # --------------------------------------------------------------
    # Class weights (softened with sqrt)
    # --------------------------------------------------------------

    train_label_ids = train_ds.labels
    train_label_ids = np.array(train_label_ids, dtype=np.int64)

    class_counts = np.bincount(
        train_label_ids,
        minlength=cfg["num_labels"],
    ).astype(np.float32)

    # Prevent divide-by-zero if a class disappeared.
    if np.any(class_counts == 0):
        missing_classes = np.where(
            class_counts == 0
        )[0].tolist()

        raise ValueError(
            "Training split is missing label IDs: "
            f"{missing_classes}. "
            "Check dataset preparation and label mapping."
        )

    use_class_weights = cfg.get("use_class_weights", False)
    class_weights = None
    if use_class_weights:
        # sqrt() softens raw inverse-frequency weighting so the rarest class
        # (pants-fire) doesn't dominate the loss/gradients early in training.
        raw_inverse_freq = class_counts.sum() / (cfg["num_labels"] * class_counts)
        class_weights = torch.tensor(
            np.sqrt(raw_inverse_freq).astype(np.float32)
        )

    log.info(
        "Training label counts: "
        + str(
            {
                i: int(count)
                for i, count in enumerate(
                    class_counts
                )
            }
        )
    )

    if class_weights is not None:
        log.info(
            "Class weights (sqrt-softened): "
            + str(
                {
                    i: float(weight)
                    for i, weight in enumerate(
                        class_weights.tolist()
                    )
                }
            )
        )
    else:
        log.info("Class weights: disabled")

    # --------------------------------------------------------------
    # FP16
    # --------------------------------------------------------------

    use_fp16 = (
        cfg["fp16"]
        and torch.cuda.is_available()
    )

    if cfg["fp16"] and not use_fp16:
        log.warning(
            "fp16 requested but no CUDA device found "
            "— falling back to fp32."
        )

    # --------------------------------------------------------------
    # Warmup steps
    # --------------------------------------------------------------
    #
    # warmup_ratio was previously dropped due to an installed-version
    # incompatibility. warmup_steps is a much older, universally-stable
    # TrainingArguments field — compute the equivalent step count manually
    # so warmup isn't silently skipped (training a pretrained transformer
    # with zero warmup risks early instability).

    grad_accum_steps = cfg.get("gradient_accumulation_steps", 1)
    steps_per_epoch = max(
        1,
        len(train_ds) // (cfg["train_batch_size"] * grad_accum_steps),
    )
    total_steps = steps_per_epoch * cfg["epochs"]
    warmup_ratio = cfg.get("warmup_ratio", 0.06)
    warmup_steps = int(warmup_ratio * total_steps)

    log.info(
        f"total_steps={total_steps}  warmup_steps={warmup_steps} "
        f"(warmup_ratio={warmup_ratio})"
    )

    # --------------------------------------------------------------
    # Training arguments
    # --------------------------------------------------------------

    args = TrainingArguments(
        output_dir=cfg["output_dir"],
        num_train_epochs=cfg["epochs"],
        per_device_train_batch_size=cfg[
            "train_batch_size"
        ],
        per_device_eval_batch_size=cfg[
            "eval_batch_size"
        ],
        gradient_accumulation_steps=grad_accum_steps,
        learning_rate=cfg["learning_rate"],
        weight_decay=cfg["weight_decay"],
        warmup_steps=warmup_steps,
        logging_steps=cfg["logging_steps"],
        eval_strategy=cfg["eval_strategy"],
        save_strategy=cfg["save_strategy"],
        load_best_model_at_end=cfg[
            "load_best_model_at_end"
        ],
        metric_for_best_model=cfg[
            "metric_for_best_model"
        ],
        fp16=use_fp16,
        dataloader_num_workers=cfg.get("dataloader_num_workers", 4),
        dataloader_pin_memory=torch.cuda.is_available(),
        report_to="none",
        seed=cfg["seed"],
    )

    # --------------------------------------------------------------
    # Trainer
    # --------------------------------------------------------------

    trainer = ClassWeightedTrainer(
        model=model,
        args=args,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        data_collator=data_collator,
        compute_metrics=compute_metrics,
        callbacks=[
            EarlyStoppingCallback(
                early_stopping_patience=cfg[
                    "early_stopping_patience"
                ]
            )
        ],
        class_weights=class_weights,
    )

    # --------------------------------------------------------------
    # Train
    # --------------------------------------------------------------

    log.info(
        f"Starting fine-tuning: "
        f"{cfg['model_name']} "
        f"on {len(train_ds)} train / "
        f"{len(val_ds)} validation examples"
    )

    trainer.train()

    # --------------------------------------------------------------
    # Final validation
    # --------------------------------------------------------------

    val_metrics = trainer.evaluate()

    log.info(
        f"Final validation metrics: {val_metrics}"
    )

    # --------------------------------------------------------------
    # Save best/raw model
    # --------------------------------------------------------------

    best_dir = (
        Path(cfg["output_dir"])
        / "best"
    )

    trainer.save_model(best_dir)

    tokenizer.save_pretrained(best_dir)

    # --------------------------------------------------------------
    # Dataset version
    # --------------------------------------------------------------

    dataset_version = load_dataset_version(
        data_dir
    )

    # --------------------------------------------------------------
    # Run metadata
    # --------------------------------------------------------------

    run_metadata = {
        "task": "6-way LIAR truthfulness classification",
        "base_model": cfg["model_name"],
        "dataset": "LIAR",
        "dataset_version": dataset_version,
        "num_labels": cfg["num_labels"],
        "label_mapping": label_mapping,
        "training_label_counts": {
            str(i): int(count)
            for i, count in enumerate(
                class_counts
            )
        },
        "class_weights": (
            {
                str(i): float(weight)
                for i, weight in enumerate(
                    class_weights.tolist()
                )
            }
            if class_weights is not None
            else None
        ),
        "hyperparameters": {
            "epochs": cfg["epochs"],
            "learning_rate": cfg["learning_rate"],
            "train_batch_size": cfg[
                "train_batch_size"
            ],
            "eval_batch_size": cfg[
                "eval_batch_size"
            ],
            "gradient_accumulation_steps": grad_accum_steps,
            "max_length": cfg["max_length"],
            "weight_decay": cfg["weight_decay"],
            "warmup_steps": warmup_steps,
            "use_metadata": use_metadata,
            "use_class_weights": use_class_weights,
            "metric_for_best_model": cfg["metric_for_best_model"],
            "seed": cfg["seed"],
            "fp16": use_fp16,
        },
        "validation_metrics": val_metrics,
        "checkpoint_path": str(best_dir),
        "next_stage": "calibration",
    }

    with open(
        Path(cfg["output_dir"])
        / "training_run.json",
        "w",
        encoding="utf-8",
    ) as f:
        json.dump(
            run_metadata,
            f,
            indent=2,
        )

    log.info(
        f"Best checkpoint saved to {best_dir}"
    )

    log.info(
        "training_run.json written — "
        "next stage: calibration."
    )


if __name__ == "__main__":
    main()